apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- spark-driver-ingress.yaml

configMapGenerator:
- name: driver-ingress-controller
  namespace: spark
  files:
  - controller.py

generatorOptions:
  disableNameSuffixHash: true
