apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: streaming-bronze
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: spark-codelabuk:latest
  sparkVersion: "3.5.3"
  mainClass: com.labuk.streaming.Orches
  mainApplicationFile: s3a://spark-jars/labuk-streaming.jar
  arguments: [ "bronze" ]